# Generated by Django 2.1.7 on 2019-02-21 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('street', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PastExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('dt_start', models.DateField()),
                ('dt_end', models.DateField(default='')),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('age', models.PositiveIntegerField(default=0)),
                ('email', models.CharField(default='', max_length=100)),
                ('desired_profession', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default=0, max_length=20)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='pastexperience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srCurriculos.Resume'),
        ),
        migrations.AddField(
            model_name='adress',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srCurriculos.Resume'),
        ),
    ]
