# Generated by Django 2.1.7 on 2019-02-21 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srCurriculos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
    ]
