# Generated by Django 2.1.7 on 2019-02-22 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srcurriculos', '0002_auto_20190222_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='address',
            name='resume',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='srcurriculos.Resume'),
        ),
        migrations.AddField(
            model_name='pastexperience',
            name='resume',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='srcurriculos.Resume'),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pastexperience',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
